### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ecca-xx** [nshpzkno/Private-Key-Generator#2]
Thanks for writing this.
Using Python 3.10.6 on macOS 12.5.
Got the following msg (see attached).
Feature, bug, or me doing it wrong?
[Terminal Saved Output.txt](https://github.com/nshpzkno/Private-Key-Generator/files/9287453/Terminal.Saved.Output.txt)

**Comment by nshpzkno** [comment]
You must install _requests_ module. Just open widows terminal and type **pip install requests** and wait until successful installation and than run my script. Should be working,

**Comment by ecca-xx** [comment]
Great to get a fast answer. 
I tried it, but 'zsh: command not found: pip'
That'll be because I have a Mac, not a Win box. Any solution for Mac?

**Comment by nshpzkno** [comment]
Try reading this https://python.engineering/installing-python-modules-on-mac/
